//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassAds1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryCallingCodes
    {
        public System.Guid Id { get; set; }
        public string country { get; set; }
        public string callingcode { get; set; }
    }
}
