//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassAds1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallary
    {
        public string id { get; set; }
        public System.DateTimeOffset createdAt { get; set; }
        public Nullable<System.DateTimeOffset> updatedAt { get; set; }
        public byte[] version { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<double> ImageSize { get; set; }
        public string ImageName { get; set; }
        public string ImageData { get; set; }
        public byte[] dataimg { get; set; }
    }
}
