//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassAds1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t1()
        {
            this.t3 = new HashSet<t3>();
        }
    
        public string id { get; set; }
        public System.DateTimeOffset createdAt { get; set; }
        public Nullable<System.DateTimeOffset> updatedAt { get; set; }
        public byte[] version { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t3> t3 { get; set; }
    }
}
