//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassAds1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t3
    {
        public string id { get; set; }
        public System.DateTimeOffset createdAt { get; set; }
        public Nullable<System.DateTimeOffset> updatedAt { get; set; }
        public byte[] version { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string t1id { get; set; }
        public string t2id { get; set; }
    
        public virtual t1 t1 { get; set; }
        public virtual t2 t2 { get; set; }
    }
}
